spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-expiration-time: 3600000
  issuer: ${JWT_ISSUER}


oauth:
  kakao:
    api-url: ${KAKAO_API_URL}
    auth-url: ${KAKAO_AUTH_URL}
    client-id: ${KAKAO_CLIENT_ID}

  naver:
    api-url: ${NAVER_API_URL}
    auth-url: ${NAVER_AUTH_URL}
    client-id: ${NAVER_CLIENT_ID}
    secret-key: ${NAVER_SECRET_KEY}

